databases:
  - name: postgres
    databaseName: Rails_Recipe_production
    user: postgres

services:
  - type: web
    name: Rails_Recipe
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Rails_Recipe
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false